#### packages ####
library(readxl)
<<<<<<< HEAD
library(ggplot2)
library(tidyverse)
library(tidyr)
library(ggpubr)
library(viridis)
library(emmeans)
library(dplyr)
=======
library(mapdata)
library(maptools)
library(ggmap)
library(ggplot2)
library(reshape2)
library(ggmap)
library(RgoogleMaps)
library(maps)
library(tidyverse)
library(mapview)
library(tidyr)
library(ggpubr)
library(viridis)
library(nortest)
library(emmeans)
library(dplyr)
library(sf)
library(multcompView)
library(multcomp)
library(mosaic)
library(car)
>>>>>>> 62781b0a763a98fee75cdc72bd926386d29265fd
